[notebook]
dir = "~/notes/meta"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/zsh"

[alias]
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
todo = 'zk edit --no-input "$ZK_NOTEBOOK_DIR/TODO.md"'
