[notebook]
dir = "~/notes/meta"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.weekly]
paths = ["weekly"]

[group.weekly.note]
filename = "{{sh 'date +%Y-w%V'}}"
extension = "md"
template = "weekly.md"

[group.meetings]
paths = ["meetings"]
[group.meetings.note]
filename = "{{format-date now '%Y-%m-%d'}}-{{id}}-{{slug title}}"
extension = "md"
template = "meeting.md"
# The charset used for random IDs.
id-charset = "alphanum"
# Length of the generated IDs.
id-length = 4
# Letter case for the random IDs.
id-case = "lower"

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/zsh"

[alias]
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
weekly = 'zk new --no-input "$ZK_NOTEBOOK_DIR/weekly"'
meeting = 'zk new --no-input "$ZK_NOTEBOOK_DIR/meetings" --title "$@"'
todo = 'zk edit --no-input "$ZK_NOTEBOOK_DIR/TODO.md"'
