[notebook]
dir = "~/notes/default"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.meetings]
paths = ["meetings"]
[group.meetings.note]
filename = "{{format-date now '%Y-%m-%d'}}-{{slug title}}"
extension = "md"
template = "meeting.md"

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/usr/bin/fish"

[alias]
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
meeting = 'zk new --no-input "$ZK_NOTEBOOK_DIR/meetings" --title "$@"'
todo = 'zk edit --no-input "$ZK_NOTEBOOK_DIR/TODO.md"'
